# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volttron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volttron',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
