# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volttron', '0002_volttron_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volttron',
            name='jupyter_port',
            field=models.IntegerField(help_text=b'Port for Jupyter Notebook'),
        ),
        migrations.AlterField(
            model_name='volttron',
            name='vc_port',
            field=models.IntegerField(help_text=b'Port for volttron central'),
        ),
        migrations.AlterField(
            model_name='volttron',
            name='vip_port',
            field=models.IntegerField(help_text=b'Instance port for the vip address'),
        ),
    ]
